#!/usr/bin/env python3
"""
Build a variable font (wght axis) from the four stroked OTF masters.

Requires: fonttools (pip install fonttools)

Inputs (generated by generateStrokes.ff):
  - gortondigitalLight.otf
  - gortondigitalRegular.otf
  - gortondigitalMedium.otf
  - gortondigitalHeavy.otf

Output:
  - GortonDigital-VF.otf (CFF2 variable font)
"""
import os
import sys
from typing import List, Tuple


def fail(message: str) -> None:
    print(f"Error: {message}", file=sys.stderr)
    sys.exit(1)


def ensure_files_exist(paths: List[str]) -> None:
    missing = [p for p in paths if not os.path.exists(p)]
    if missing:
        fail("Missing masters: " + ", ".join(missing))


def build_variable_font(output_path: str) -> None:
    try:
        from fontTools.designspaceLib import (
            DesignSpaceDocument,
            AxisDescriptor,
            SourceDescriptor,
        )
        from fontTools.varLib import build as varlib_build
    except ImportError:
        fail(
            "fonttools is required. Install with 'pip install fonttools' or 'pipx install fonttools'."
        )

    masters: List[Tuple[str, int, str]] = [
        ("gortondigitalLight.otf", 300, "Light"),
        ("gortondigitalRegular.otf", 400, "Regular"),
        ("gortondigitalMedium.otf", 500, "Medium"),
        ("gortondigitalHeavy.otf", 700, "Heavy"),
    ]

    ensure_files_exist([m[0] for m in masters])

    doc = DesignSpaceDocument()

    axis = AxisDescriptor()
    axis.name = "wght"
    axis.tag = "wght"
    axis.minimum = 300
    axis.default = 400
    axis.maximum = 700
    doc.addAxis(axis)

    for path, wght, name in masters:
        src = SourceDescriptor()
        src.path = path
        src.name = name
        src.location = {"wght": wght}
        doc.addSource(src)

    vf = varlib_build(doc)
    vf.save(output_path)
    print(f"Wrote {output_path}")


def main() -> None:
    output_path = "GortonDigital-VF.otf"
    # Allow optional output name as first arg
    if len(sys.argv) > 1:
        output_path = sys.argv[1]
    build_variable_font(output_path)


if __name__ == "__main__":
    main()


